// @ts-check
import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    // next-env.d.ts is generated by Next and is a triple-slash reference by design.
    ignores: ['node_modules/**', '.next/**', 'dist/**', 'coverage/**', 'next-env.d.ts'],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      parserOptions: { ecmaVersion: 2022, sourceType: 'module' },
    },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },

  // ───────────────────────────────────────────────────────────────────────────
  // THE BOUNDARY RULE.
  //
  // src/core is the brain: pure, deterministic, dependency-free. It must never
  // reach for a database, an HTTP client, a queue, or the wall clock. Every
  // function takes its inputs as arguments and returns a decision.
  //
  // This is what makes Stage 1 finished *permanently* — nothing built in later
  // stages can import into core, so nothing built later can break it.
  // ───────────────────────────────────────────────────────────────────────────
  {
    files: ['src/core/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: [
                '**/db/**',
                '**/adapters/**',
                '**/workflows/**',
                '**/app/**',
                '@db/*',
                '@adapters/*',
                '@workflows/*',
              ],
              message:
                'src/core must stay pure. Pass data in as arguments, return decisions out. ' +
                'I/O belongs in src/adapters, src/db or src/workflows.',
            },
            {
              group: ['node:*', 'fs', 'path', 'crypto', 'http', 'https', 'child_process'],
              message:
                'src/core must stay pure — no Node built-ins. If you need randomness or ' +
                'hashing, use the deterministic helpers in src/core (e.g. cohort.ts).',
            },
          ],
        },
      ],

      // Time is an input, never an ambient fact. Every core function that needs
      // "now" takes `now: Date` as a parameter. This is what lets us unit-test
      // "9:04pm IST on a Sunday during an ICICI outage" without a staging env.
      //
      // Deriving a date from a supplied timestamp — `new Date(now.getTime() + ms)` —
      // is pure and allowed. Reading the wall clock is not.
      'no-restricted-syntax': [
        'error',
        {
          selector: "NewExpression[callee.name='Date'][arguments.length=0]",
          message:
            'src/core must not read ambient time. Accept `now: Date` as a parameter, ' +
            'or derive from a supplied timestamp: new Date(now.getTime() + ms).',
        },
        {
          selector: "CallExpression[callee.object.name='Date'][callee.property.name='now']",
          message: 'src/core must not read the wall clock. Accept `now: Date` as a parameter.',
        },
        {
          selector: "CallExpression[callee.object.name='Math'][callee.property.name='random']",
          message:
            'src/core must be deterministic. Use the seeded hash in cohort.ts for anything ' +
            'that needs to look random but must replay identically.',
        },
      ],
    },
  },

  {
    files: ['tests/**/*.ts', 'scripts/**/*.ts', '*.config.ts', '*.config.mts'],
    rules: {
      'no-restricted-syntax': 'off',
      // Build scripts report to a terminal; that is their whole job.
      'no-console': 'off',
    },
  },
);
